### ISSUE TITLE
error and display of render

### ISSUE THREAD

**Issue by tysun** [DanielStormApps/Create-Random-Bezier-Path#1] opened 2016-07-04 20:55 UTC
Hi Daniel

When I run it in the playground `let path = createBezierPath()`  gives an error. 
**Use of unresolved identifier 'createBezierPath'** 

Is there a missing class called `createBezierPath`?

Thanks

**Comment by DanielStormApps** [comment] 2016-07-04 22:46
Hey @tysun. I'm not entirely sure what the issue is but it can be ignored. The Playground still runs the code. Example:

![screen shot 2016-07-04 at 6 42 36 pm](https://cloud.githubusercontent.com/assets/10573489/16570635/927c132e-4217-11e6-8d0a-6ff058ca2d38.png)

**Comment by tysun** [comment] 2016-07-05 03:02
I figured it out. I will fork and push Swift 3 updates and correct declaration to you.

**Comment by tysun** [comment] 2016-07-05 03:12
Sent pull request

**Comment by DanielStormApps** [comment] 2016-07-05 11:47
@tysun Merged. Thanks!

**Closed as completed by DanielStormApps** 2016-07-05 11:47 UTC
